name: Release

on:
  release:
    types: [released]

jobs:
  trigger-conan-index:
    runs-on: ubuntu-24.04
    name: "Trigger conan-index workflow"

    steps:
    - uses: actions/checkout@v4

    - name: "Trigger conan-index workflow"
      run: |
        .github/trigger-conan-index.ps1 \
          -GitHubSourceRepository ${{ github.repository }} \
          -GitHubSourceReference '${{ github.ref }}' \
          -GitHubIndexRepository '${{ github.repository_owner }}/conan-index' \
          -GitHubIndexToken ${{ secrets.CONAN_INDEX_TOKEN }} \
          -PackageBase ${{ github.event.repository.name }}
