on:
  release:
    types: [released]

jobs:
  trigger-conan-index:
    runs-on: ubuntu-24.04
    name: "Trigger conan-index workflow"

    steps:
    - name: "Trigger conan-index workflow"
      run: |
        .github/trigger-conan-index.ps1 \
          -GitHubSourceRepository ${{ github.repository }} \
          -GitHubSourceReference '${{ github.ref }}' \
          -GitHubIndexUser ${{ github.event.repository.owner }} \
          -GitHubIndexRepository conan-index \
          -GitHubIndexToken ${{ secrets.CONAN_INDEX_TOKEN }} \
          -PackageBase ${{ github.event.repository.name }}
