name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cxx-testing:
    uses: vasama/actions/.github/workflows/cxx-testing.yml@main
    with:
      setup: .github/Setup-CxxProject.ps1

#jobs:
#  testing-linux:
#    name: Linux - ${{ matrix.tool }} - ${{ matrix.config }}
#
#    runs-on: ubuntu-latest
#    container:
#      image: ghcr.io/vasama/actions-ubuntu:v0_3
#
#    strategy:
#      fail-fast: false
#      matrix:
#        tool:
#        - clang
#        - clang/tidy
#        - gcc
#        config:
#        - Debug
#        - Release
#        exclude:
#          - tool: clang/tidy
#            config: Release
#
#    steps:
#    - uses: actions/checkout@v7
#    - uses: vasama/actions/setup@main
#    - uses: vasama/actions/setup-conan-index@main
#
#    - name: Add local conan package
#      shell: pwsh
#      run: |
#        conan create ./conan
#        conan create ./cmake
#
#    - uses: vasama/actions/test-cxx-project@main
#      with:
#        tool: ${{ matrix.tool }}
#        config: ${{ matrix.config }}
#
#  testing-windows:
#    name: Windows - ${{ matrix.tool }} - ${{ matrix.config }}
#
#    runs-on: windows-2025-vs2026
#
#    strategy:
#      fail-fast: false
#      matrix:
#        tool:
#        - clang
#        - msvc
#        - msvc/intellisense
#        config:
#        - Debug
#        - Release
#        exclude:
#        - tool: msvc/intellisense
#          config: Release
#
#    steps:
#    - uses: actions/checkout@v7
#    - uses: vasama/actions/setup@main
#    - uses: vasama/actions/setup-conan-windows@main
#    - uses: vasama/actions/setup-conan-index@main
#
#    - name: Add local conan package
#      shell: pwsh
#      run: |
#        conan create ./conan
#        conan create ./cmake
#
#    - uses: vasama/actions/test-cxx-project@main
#      with:
#        tool: ${{ matrix.tool }}
#        config: ${{ matrix.config }}
