name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cxx-testing:
    uses: vasama/actions/.github/workflows/cxx-testing.yml@main
    with:
      setup: .github/Setup-CxxProject.ps1
